# Generated by Django 5.2.11 on 2026-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
