# Generated by Django 5.2.11 on 2026-03-04 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0002_flight_departure_date_flight_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
