# Generated by Django 5.2.11 on 2026-03-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0003_alter_flight_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
