# Generated by Django 5.2.11 on 2026-03-04 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0004_flight_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', 'purse'), ('b', 'backpack'), ('c', 'carry-on luggage'), ('s', 'suitcase'), ('br', 'briefcase')], default='c', max_length=50)),
                ('size', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large')], default='b', max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.flight')),
            ],
        ),
    ]
