# Generated by Django 5.2.11 on 2026-03-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0005_luggage'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggage',
            name='items',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
